#
# requires the following gitlab secret variables
#
# - GCPAPPENGINEREPO_USERNAME
# - GCPAPPENGINEREPO_PASSWORD
# - GCPAPPENGINEREPO_REPO_URL
#

image: maven:3.5.3-jdk-8

before_script:
  - export BASELINE=2.0.0
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)

stages:
  - build-package-push

build-package-push:
  stage: build-package-push
  script:
    - echo "REVISION=$REVISION"
    - echo "GCPAPPENGINEREPO_URL=$GCPAPPENGINEREPO_URL"
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          clean deploy \
          -Dgcpappenginerepo-deploy \
          -Dgcpappenginerepo-deploy.repositoryUrl=$GCPAPPENGINEREPO_URL \
          -Drevision=$REVISION \
          $CORE_ADDITIONAL_OPTS

#
# Previously this script also uploaded to a Sonatype Nexus.
# Here's the stuff that did it.
#
# - NEXUS_USERNAME
# - NEXUS_PASSWORD
# - NEXUS_REPO_URL
#
#
#    - >
#      mvn -s .m2/settings.xml \
#          --batch-mode \
#          clean deploy \
#          -Drevision=$REVISION \
#          -Dnexus-deploy \
#          -Dnexus-deploy.repositoryUrl=$NEXUS_REPO_URL \
#          $CORE_ADDITIONAL_OPTS
